"""Initial schema

Revision ID: f6b529db3246
Revises: 
Create Date: 2026-10-07 23:04:50.782213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6b529db3246'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('creator_sessions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('expires_at', sa.String(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_creator_sessions_expires_at'), 'creator_sessions', ['expires_at'], unique=False)
    op.create_index(op.f('ix_creator_sessions_token_hash'), 'creator_sessions', ['token_hash'], unique=True)
    op.create_table('creators',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('form_versions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.String(), nullable=False),
    sa.Column('questions_snapshot', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_form_versions_form_id'), 'form_versions', ['form_id'], unique=False)
    op.create_table('forms',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('creator_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('published_version_id', sa.String(), nullable=True),
    sa.Column('slug', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['creators.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['published_version_id'], ['form_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_forms_creator_id'), 'forms', ['creator_id'], unique=False)
    op.create_index(op.f('ix_forms_slug'), 'forms', ['slug'], unique=True)
    op.create_index(op.f('ix_forms_status'), 'forms', ['status'], unique=False)
    op.create_index(op.f('ix_forms_updated_at'), 'forms', ['updated_at'], unique=False)
    op.create_table('questions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('required', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('settings', sa.String(), nullable=False),
    sa.Column('created_at', sa.String(), nullable=False),
    sa.Column('updated_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_form_id'), 'questions', ['form_id'], unique=False)
    op.create_table('submissions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('form_id', sa.String(), nullable=False),
    sa.Column('form_version_id', sa.String(), nullable=False),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('submitted_at', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['form_id'], ['forms.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['form_version_id'], ['form_versions.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_submissions_form_id'), 'submissions', ['form_id'], unique=False)
    op.create_index(op.f('ix_submissions_form_version_id'), 'submissions', ['form_version_id'], unique=False)
    op.create_index(op.f('ix_submissions_submitted_at'), 'submissions', ['submitted_at'], unique=False)
    op.create_table('answers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('submission_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('value_text', sa.String(), nullable=True),
    sa.Column('value_number', sa.Float(), nullable=True),
    sa.Column('value_boolean', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_answers_submission_id'), 'answers', ['submission_id'], unique=False)
    op.create_table('question_options',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_options_question_id'), 'question_options', ['question_id'], unique=False)
    op.create_table('answer_option_selections',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('answer_id', sa.String(), nullable=False),
    sa.Column('option_id', sa.String(), nullable=False),
    sa.Column('option_label', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['answer_id'], ['answers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answer_option_selections_answer_id'), 'answer_option_selections', ['answer_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_answer_option_selections_answer_id'), table_name='answer_option_selections')
    op.drop_table('answer_option_selections')
    op.drop_index(op.f('ix_question_options_question_id'), table_name='question_options')
    op.drop_table('question_options')
    op.drop_index(op.f('ix_answers_submission_id'), table_name='answers')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_submissions_submitted_at'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_form_version_id'), table_name='submissions')
    op.drop_index(op.f('ix_submissions_form_id'), table_name='submissions')
    op.drop_table('submissions')
    op.drop_index(op.f('ix_questions_form_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_forms_updated_at'), table_name='forms')
    op.drop_index(op.f('ix_forms_status'), table_name='forms')
    op.drop_index(op.f('ix_forms_slug'), table_name='forms')
    op.drop_index(op.f('ix_forms_creator_id'), table_name='forms')
    op.drop_table('forms')
    op.drop_index(op.f('ix_form_versions_form_id'), table_name='form_versions')
    op.drop_table('form_versions')
    op.drop_table('creators')
    op.drop_index(op.f('ix_creator_sessions_token_hash'), table_name='creator_sessions')
    op.drop_index(op.f('ix_creator_sessions_expires_at'), table_name='creator_sessions')
    op.drop_table('creator_sessions')
    # ### end Alembic commands ###
